# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transposerGui.ui'
#
# Created: Wed Jan 21 12:30:51 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Transposer(object):
    def setupUi(self, Transposer):
        Transposer.setObjectName(_fromUtf8("Transposer"))
        Transposer.resize(800, 600)
        self.centralwidget = QtGui.QWidget(Transposer)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.transpose = QtGui.QPushButton(self.centralwidget)
        self.transpose.setGeometry(QtCore.QRect(250, 440, 98, 27))
        self.transpose.setObjectName(_fromUtf8("transpose"))
        self.exit = QtGui.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(390, 440, 98, 27))
        self.exit.setObjectName(_fromUtf8("exit"))
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(193, 180, 371, 241))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.fromKeylistWidget = QtGui.QListWidget(self.centralwidget)
        self.fromKeylistWidget.setGeometry(QtCore.QRect(150, 180, 31, 241))
        self.fromKeylistWidget.setObjectName(_fromUtf8("fromKeylistWidget"))
        item = QtGui.QListWidgetItem()
        self.fromKeylistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.fromKeylistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.fromKeylistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.fromKeylistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.fromKeylistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.fromKeylistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.fromKeylistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.fromKeylistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.fromKeylistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.fromKeylistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.fromKeylistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.fromKeylistWidget.addItem(item)
        self.toKeylistWidget = QtGui.QListWidget(self.centralwidget)
        self.toKeylistWidget.setGeometry(QtCore.QRect(580, 180, 31, 241))
        self.toKeylistWidget.setObjectName(_fromUtf8("toKeylistWidget"))
        item = QtGui.QListWidgetItem()
        self.toKeylistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.toKeylistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.toKeylistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.toKeylistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.toKeylistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.toKeylistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.toKeylistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.toKeylistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.toKeylistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.toKeylistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.toKeylistWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.toKeylistWidget.addItem(item)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 160, 66, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(95, 156, 91, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(580, 150, 91, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        Transposer.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Transposer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        Transposer.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Transposer)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Transposer.setStatusBar(self.statusbar)

        self.retranslateUi(Transposer)
        QtCore.QObject.connect(self.exit, QtCore.SIGNAL(_fromUtf8("clicked()")), Transposer.close)
        QtCore.QMetaObject.connectSlotsByName(Transposer)

    def retranslateUi(self, Transposer):
        Transposer.setWindowTitle(_translate("Transposer", "Transposer", None))
        self.transpose.setText(_translate("Transposer", "Transpose", None))
        self.exit.setText(_translate("Transposer", "Exit", None))
        self.fromKeylistWidget.setToolTip(_translate("Transposer", "<html><head/><body><p>Mark the original key</p></body></html>", None))
        __sortingEnabled = self.fromKeylistWidget.isSortingEnabled()
        self.fromKeylistWidget.setSortingEnabled(False)
        item = self.fromKeylistWidget.item(0)
        item.setText(_translate("Transposer", "c", None))
        item = self.fromKeylistWidget.item(1)
        item.setText(_translate("Transposer", "c#", None))
        item = self.fromKeylistWidget.item(2)
        item.setText(_translate("Transposer", "d", None))
        item = self.fromKeylistWidget.item(3)
        item.setText(_translate("Transposer", "d#", None))
        item = self.fromKeylistWidget.item(4)
        item.setText(_translate("Transposer", "e", None))
        item = self.fromKeylistWidget.item(5)
        item.setText(_translate("Transposer", "f", None))
        item = self.fromKeylistWidget.item(6)
        item.setText(_translate("Transposer", "f#", None))
        item = self.fromKeylistWidget.item(7)
        item.setText(_translate("Transposer", "g", None))
        item = self.fromKeylistWidget.item(8)
        item.setText(_translate("Transposer", "g#", None))
        item = self.fromKeylistWidget.item(9)
        item.setText(_translate("Transposer", "a", None))
        item = self.fromKeylistWidget.item(10)
        item.setText(_translate("Transposer", "a#", None))
        item = self.fromKeylistWidget.item(11)
        item.setText(_translate("Transposer", "b", None))
        self.fromKeylistWidget.setSortingEnabled(__sortingEnabled)
        self.toKeylistWidget.setToolTip(_translate("Transposer", "<html><head/><body><p>Mark the key to transpose into</p></body></html>", None))
        __sortingEnabled = self.toKeylistWidget.isSortingEnabled()
        self.toKeylistWidget.setSortingEnabled(False)
        item = self.toKeylistWidget.item(0)
        item.setText(_translate("Transposer", "c", None))
        item = self.toKeylistWidget.item(1)
        item.setText(_translate("Transposer", "c#", None))
        item = self.toKeylistWidget.item(2)
        item.setText(_translate("Transposer", "d", None))
        item = self.toKeylistWidget.item(3)
        item.setText(_translate("Transposer", "d#", None))
        item = self.toKeylistWidget.item(4)
        item.setText(_translate("Transposer", "e", None))
        item = self.toKeylistWidget.item(5)
        item.setText(_translate("Transposer", "f", None))
        item = self.toKeylistWidget.item(6)
        item.setText(_translate("Transposer", "f#", None))
        item = self.toKeylistWidget.item(7)
        item.setText(_translate("Transposer", "g", None))
        item = self.toKeylistWidget.item(8)
        item.setText(_translate("Transposer", "g#", None))
        item = self.toKeylistWidget.item(9)
        item.setText(_translate("Transposer", "a", None))
        item = self.toKeylistWidget.item(10)
        item.setText(_translate("Transposer", "a#", None))
        item = self.toKeylistWidget.item(11)
        item.setText(_translate("Transposer", "b", None))
        self.toKeylistWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Transposer", "Chords:", None))
        self.label_2.setText(_translate("Transposer", "Original key:", None))
        self.label_3.setText(_translate("Transposer", "New key:", None))

